export VULKAN_SDK_ROOT=~/vulkan/VulkanSDK
export VULKAN_SDK_VERSION=1.0.46.0
export VULKAN_SDK_ARCH=x86_64
export VULKAN_SDK=${VULKAN_SDK_ROOT}/${VULKAN_SDK_VERSION}/${VULKAN_SDK_ARCH}

export LD_LIBRARY_PATH=$VULKAN_SDK/lib:$LD_LIBRARY_PATH